version: 0.2

env:
  parameter-store:
    DOCKER_REG_USERNAME: /myapp/docker-credentials/username
    DOCKER_REG_PASSWORD: /myapp/docker-credentials/password
    DOCKER_REG_URL: /myapp/docker-credentials/url

phases:
  install:
    runtime-versions:
      python: 3.11

  pre_build:
    commands:
      - pip install -r requirements.txt
      - echo Logging in to Docker...
      - echo "$DOCKER_REG_PASSWORD" | docker login "$DOCKER_REG_URL" --username "$DOCKER_REG_USERNAME" --password-stdin

  build:
    commands:
      - echo "Building Docker Image"
      - docker build -t "$DOCKER_REG_URL/$DOCKER_REG_USERNAME/simple-python-flask-service:latest" .
      - docker push "$DOCKER_REG_URL/$DOCKER_REG_USERNAME/simple-python-flask-service:latest"
      
      # Create a deployment artifact (zip file)
      - echo "Creating deployment package"
      - zip -r deployment.zip . -x "*.git*" "*.dockerignore*" "*.env*"

  post_build:
    commands:
      - echo "Build completed successfully"

# Add this artifacts section to upload to S3
artifacts:
  files:
    - deployment.zip
  discard-paths: yes
  base-directory: .
